name: Run Playwright Tests on Dev2

on:
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests for dev2Checkout, dev2Moyasar, and dev2Ngenius
        run: |
          echo "Running tests in dev2Checkout, dev2Moyasar, and dev2Ngenius"
          npx playwright test --config=playwright.config.js --project=chromium tests/dev2Checkout/**/*.spec.js tests/dev2Moyasar/**/*.spec.js tests/dev2Ngenius/**/*.spec.js
