name: Run Playwright Tests on Dev2

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - dev2Checkout
          - dev2Moyasar
          - dev2Ngenius

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright dependencies
        uses: microsoft/playwright-github-action@v1

      - name: Run Playwright tests for ${{ matrix.folder }}
        run: npx playwright test ./tests/${{ matrix.folder }} --project=chromium
